FROM nginx:alpine
COPY index.html /usr/share/nginx/html/index.html
COPY nginx.conf.template /etc/nginx/templates/default.conf.template
RUN chmod 644 /usr/share/nginx/html/index.html /etc/nginx/templates/default.conf.template
